image: node:14.9.0

variables:
  FF_USE_FASTZIP: "true"

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - node_modules/

.pull_cached_node_modules:
  cache:
    untracked: true
    key: ${CI_COMMIT_SHORT_SHA}
    policy: pull

stages:
  - build
  - test

Build system:
  stage: build
  script:
    - npm ci

Code Linting:
  stage: test

  before_script:
    - npm install -g @angular/cli@11.2.6
    - npm install
  script:
    - npm run lint

Run tests:
  stage: test
  extends: .pull_cached_node_modules
  before_script:
    - npm install
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROMIUM_BIN=/usr/bin/google-chrome
  script:
    - npm run test:ci
